### PR TITLE
Jobs

### PR DESCRIPTION
**Pull request by TimAbraldes**
- Initial impl of crawler driver
- Add urlJobPopulator and a mock backend
- Create urlJobProcessor from existing crawler scaffold code
- Split urlStore from dataStore (remove push and pop url functions from dataStore)

### CODE REVIEW

**Comment by TimAbraldes** [comment]
This will close #13

**Comment by zalun** [comment]
All fine, but (oh boy!) how I wish you would add comments ...

**Comment by TimAbraldes** [comment]
> All fine, but (oh boy!) how I wish you would add comments ...

Sure, can do!

**Comment by TimAbraldes** [comment]
Merged per https://github.com/mozilla/prowac/pull/15#issuecomment-182961849

**Pull request merged**
